"""Contratos formais (Protocol) entre camadas do Quimera."""
from __future__ import annotations

from typing import Any, Callable, Protocol, runtime_checkable


@runtime_checkable
class IRenderer(Protocol):
    """Abstração de renderização de mensagens no terminal (sistema, agente, erro, aviso)."""
    def show_system(self, msg: str) -> None: ...
    def show_agent(self, agent: str, msg: str) -> None: ...
    def show_error(self, msg: str) -> None: ...
    def show_warning(self, msg: str) -> None: ...


@runtime_checkable
class ISessionStorage(Protocol):
    """Persistência e restauração de sessão (logs textuais + snapshot JSON)."""
    def session_id(self) -> str: ...
    def append_log(self, role: str, content: str) -> None: ...
    def load_last_session(self) -> dict: ...
    def save_history(self, history: list, shared_state: dict | None = ...) -> None: ...


@runtime_checkable
class IAgentClient(Protocol):
    """Cliente de chamada a agentes externos (envio de prompt + cancelamento)."""
    def call(self, agent: str, prompt: str, history: list) -> str: ...
    def cancel(self) -> None: ...


@runtime_checkable
class IPluginResolver(Protocol):
    """Resolução de plugins por nome e listagem de todos os plugins registrados."""
    def get(self, name: str): ...

    @property
    def plugins(self) -> list: ...


@runtime_checkable
class IAgentPool(Protocol):
    """Coleção mutável de agentes disponíveis com suporte a rotação e agente primário."""
    @property
    def agents(self) -> list[str]: ...

    @property
    def primary(self) -> str | None: ...

    def add(self, name: str) -> None: ...
    def remove(self, name: str) -> None: ...
    def set(self, agents: list[str]) -> None: ...
    def rotate(self) -> None: ...
    def __contains__(self, name: str) -> bool: ...
    def __iter__(self): ...
    def __len__(self) -> int: ...
    def __bool__(self) -> bool: ...


class PluginResolverAdapter:
    """Adapter explícito para resolução de plugins sem depender de QuimeraApp."""

    def __init__(self, registry: Any, normalize: Callable[[object], str | None]):
        self._registry = registry
        self._normalize = normalize

    def get(self, name: str):
        normalized_name = self._normalize(name)
        if not normalized_name:
            return None
        if self._registry is not None:
            return self._registry.get(normalized_name)
        return None

    @property
    def plugins(self) -> list:
        if self._registry is None:
            return []
        return list(self._registry.all_plugins())


@runtime_checkable
class ISessionServices(Protocol):
    """Serviços de ciclo de vida da sessão: persistência de mensagens, sumarização automática e shutdown."""
    def persist_message(self, role: str, content: str) -> None: ...
    def maybe_auto_summarize(self, preferred_agent: str | None = ...) -> None: ...
    def shutdown(self) -> None: ...


@runtime_checkable
class IInputServices(Protocol):
    """Serviços de entrada do usuário: leitura via terminal, editor de texto e arquivos."""
    def read_user_input(self, prompt: str, timeout: int) -> str | None: ...
    def read_from_editor(self) -> str | None: ...
    def read_from_file(self, path_str: str) -> str | None: ...
    def suspend_nonblocking(self) -> None: ...
    def resume_nonblocking(self) -> None: ...
