"""Contratos formais (Protocol) entre camadas do Quimera."""
from __future__ import annotations

from typing import Any, Callable, Protocol, runtime_checkable

from quimera.prompt_templates import PromptText
from quimera import profiles as _global_profiles


@runtime_checkable
class IRenderer(Protocol):
    """Contrato de renderer usado pelas camadas de aplicação."""
    supports_agent_feed: bool
    supports_structured_agent_activity: bool

    def show_system(self, msg: str) -> None: ...
    def show_agent(self, agent: str, msg: str) -> None: ...
    def show_error(self, msg: str) -> None: ...
    def show_warning(self, msg: str) -> None: ...
    def show_banner(self, message: str) -> None: ...
    def show_system_neutral(self, message: str) -> None: ...
    def show_approval(self, message: str) -> None: ...
    def show_feed(self, message: str, agent: str | None = ..., muted: bool = ...) -> None: ...
    def show_plain(self, message: str, agent: str | None = ..., muted: bool = ...) -> None: ...
    def show_turn_summary(self, agent: str | None, detail: dict) -> None: ...
    def show_message(self, agent: str, content: str, render_mode: str = ...) -> None: ...
    def show_no_response(self, agent: str) -> None: ...
    def show_delegation(self, from_agent: str, to_agent: str, task: str | None = ..., **kwargs) -> None: ...
    def show_prompt_preview(self, agent: str, preview: str) -> None: ...
    def notify_agent_retry(self, agent: str, *, reason: str, attempt: int, limit: int, detail: str = ...) -> None: ...
    def notify_agent_failover(self, agent: str, *, target: str, message: str = ...) -> None: ...
    def update_agent_transient(self, agent: str, message: str) -> None: ...
    def clear_agent_transient(self, agent: str) -> None: ...
    def commit_agent_stream(self, agent: str, render_mode: str = ...) -> bool: ...
    def flush(self, timeout: float = ...) -> None: ...
    def flush_quick(self, timeout: float = ...) -> bool | None: ...
    def signal_restore_history(self) -> None: ...
    def set_summarizing(self, active: bool) -> None: ...
    def set_prompt_integration(self, is_active_fn, run_above_fn) -> None: ...
    def log_debug_event(self, event: str, **payload) -> None: ...
    def close(self, timeout: float = ...) -> None: ...
    def running_status(self, initial: str = ..., agent: str | None = ...): ...
    def print_direct(self, message: str) -> None: ...
    def clear_screen(self) -> None: ...
    def selection_window(self, **kwargs): ...
    def approval_window(self, **kwargs): ...
    def agent_window_controller(self, agent: str): ...
    def set_profile_resolver(self, resolver) -> None: ...
    def set_orchestrator(self, agent_name: str | None) -> None: ...


@runtime_checkable
class ISessionStorage(Protocol):
    """Persistência e restauração de sessão (logs textuais + snapshot JSON)."""
    def session_id(self) -> str: ...
    def append_log(self, role: str, content: str) -> None: ...
    def load_last_session(self) -> dict: ...
    def save_history(self, history: list, shared_state: dict | None = ...) -> None: ...


@runtime_checkable
class IAgentClient(Protocol):
    """Cliente de chamada a agentes externos (envio de prompt + cancelamento)."""
    def call(self, agent: str, prompt: PromptText, history: list) -> str: ...
    def cancel(self) -> None: ...


@runtime_checkable
class IProfileResolver(Protocol):
    """Resolução de perfis por nome e listagem de todos os perfis registrados."""
    def get(self, name: str): ...

    @property
    def profiles(self) -> list: ...


@runtime_checkable
class IAgentPool(Protocol):
    """Coleção mutável de agentes disponíveis com suporte a rotação e agente primário."""
    @property
    def agents(self) -> list[str]: ...

    @property
    def primary(self) -> str | None: ...

    def add(self, name: str) -> None: ...
    def remove(self, name: str) -> None: ...
    def set(self, agents: list[str]) -> None: ...
    def rotate(self) -> None: ...
    def freeze(self, agent_name: str) -> None: ...
    def unfreeze(self) -> None: ...
    @property
    def frozen_agent(self) -> str | None: ...
    def __contains__(self, name: str) -> bool: ...
    def __iter__(self): ...
    def __len__(self) -> int: ...
    def __bool__(self) -> bool: ...


class ProfileResolverAdapter:
    """Adapter explícito para resolução de profiles sem depender de QuimeraApp."""

    def __init__(self, registry: Any, normalize: Callable[[object], str | None]):
        self._registry = registry
        self._normalize = normalize

    def get(self, name: str):
        normalized_name = self._normalize(name)
        if not normalized_name:
            return None
        if self._registry is not None:
            return self._registry.get(normalized_name)
        return _global_profiles.get(normalized_name)

    @property
    def profiles(self) -> list:
        if self._registry is not None:
            return list(self._registry.all_profiles())
        return list(_global_profiles.all_profiles())

    def get_profiles_list(self) -> list:
        return list(self._registry.all_profiles()) if self._registry is not None else list(_global_profiles.all_profiles())

    def active_profiles(self, agent_pool) -> list:
        """Retorna os perfis válidos dos agentes ativos no pool."""
        result = []
        for agent_name in agent_pool:
            profile = self.get(agent_name)
            if profile is not None:
                result.append(profile)
        return result

    def configure_mcp_socket(self, agent_pool, socket_path: str | None, token: str | None = None) -> None:
        """Propaga o socket MCP e token para os perfis dos agentes ativos na sessão."""
        for profile in self.active_profiles(agent_pool):
            config_setter = getattr(profile, "set_mcp_socket_config", None)
            if callable(config_setter):
                config_setter(socket_path, token)
            else:
                path_setter = getattr(profile, "set_mcp_socket_path", None)
                if callable(path_setter):
                    path_setter(socket_path)

    def configure_mcp_http(self, agent_pool, url: str | None, token: str | None = None) -> None:
        """Propaga endpoint e token MCP HTTP para perfis de agentes ativos."""
        for profile in self.active_profiles(agent_pool):
            config_setter = getattr(profile, "set_mcp_http_config", None)
            if callable(config_setter):
                config_setter(url, token)


@runtime_checkable
class ISessionServices(Protocol):
    """Serviços de ciclo de vida da sessão: persistência de mensagens, sumarização automática e shutdown."""
    def persist_message(
        self,
        role: str,
        content: str,
        *,
        return_history_snapshot: bool = ...,
    ) -> list | None: ...
    def maybe_auto_summarize(self, preferred_agent: str | None = ...) -> None: ...
    def shutdown(self, *, interrupted: bool = ...) -> None: ...


@runtime_checkable
class IInputServices(Protocol):
    """Serviços de entrada do usuário: leitura via terminal, editor de texto e arquivos."""
    def read_user_input(self, prompt: str, timeout: int) -> str | None: ...
    def read_from_editor(self) -> str | None: ...
    def read_from_file(self, path_str: str) -> str | None: ...
    def suspend_nonblocking(self) -> None: ...
    def resume_nonblocking(self) -> None: ...
